---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FXEQV713CW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FXEQV713CW');
</script>

### 人物

- 名前
  - 金山 隼人（Hayato, Kanayama）

- 国籍
  - 日本（Japan）

- 性別
  - 男（Male）
  
- 生年
  - 1999


### 略歴

- 2024.03 修士（経済学）；早稲田大学大学院 経済学研究科
- 2022.03 学士（経済学）；高知工科大学 経済・マネジメント学群

\

### 業績

\ 

#### Working paper

- [Discontinuous or Kinked Response? Dynamics of Unemployment Insurance and Public Assistance under the COVID-19 Crisis (with Michihito Ando, Masato Furuichi) ](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4617281)

#### 学会発表

- [Asian and Australasian Society of Labour Economics 2023 Conference](https://virtual.oxfordabstracts.com/#/event/public/4290/submission/245)
- [2023年度 労働経済学コンファレンス（ポスターセッション）](https://sites.google.com/site/kansailabor/conference/26th?authuser=0)

\ 

### 奨学金・研究費助成

- 早稲田大学 オープン・イノベーション・エコシステム挑戦的研究プログラム（WSPRING）, 2024年4月--2027年3月（予定）.
  - 生活相当額：年額240万円
  - 研究費：年額50万円

\

#### RA・SA・TA

- RA; Research Assistant
	1. 立教大学 経済学部 リサーチ・アシスタント（2022.05 - 現在）
	1. 早稲田大学 組織経済実証研究所 リサーチ・アシスタント（2023.02 - 現在）
	1. 早稲田大学 政治経済学術院 リサーチ・アシスタント（2022.06 - 2022.08） 

\ 

- SA; Student Assistant
	1. 高知工科大学 SA ; 2021年度 アンケート調査法（日道 俊之）
	1. 高知工科大学 SA ; 2021年度 統計学2（矢内 勇生）
	
\	
	
- TA; Teaching Assistant
  1. Population Economics ; Spring semester, 2024 (Yoshida, M)
  1. Micro Economics 1 ; Spring semester, 2024 (Owan, H)
	1. Population Economics；Spring semester, 2023 (YOSHIDA, M)
	1. 計量経済学Ⅰ 01；2023年度 春学期（近藤 康之）
	1. 計量分析（政治） 01；2023年度 春学期（浅野 正彦）
	1. 計量経済学Ⅱ 01；2023年度 秋学期（近藤 康之）

\ 

### プログラミングスキル

\ 

#### 計算および分析


- R（Tidyverse R）
- Python

\ 

#### 文章執筆


- Markdown
- LaTeX

\ 

### データ・コード管理

- [GitHub](https://github.com/kanayama8810)

\ 

### 所属学会

- 日本経済学会

（`r Sys.Date()` 最終更新 ）
