---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FXEQV713CW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FXEQV713CW');
</script>

### Information

- Name(Last, Family)
  - Hayato Kanayama

- PhD student at [Waseda University](https://www.waseda.jp/fpse/gse/en/)

- Country
  - Japan

- E-mail
  - ha13yato`@`toki.waseda.jp

### Education

- Master Program in Economics (Apr 2022 - March 2024, Waseda University)
- B.A. in Economics (March 2022, Kochi University of Technology)

\

### Working Papers

- [Discontinuous or Kinked Response? Dynamics of Unemployment Insurance and Public Assistance under the COVID-19 Crisis (with Michihito Ando and Masato Furuichi)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4617281)



\ 

### Conference Presentations

- [Asian and Australasian Society of Labour Economics 2023 Conference](https://virtual.oxfordabstracts.com/#/event/public/4290/submission/245)
- [Labor Economics Conference (2023). The Returns to Workplace Schmoozing with Bosses: Evidence from a Large Manufacturing Company](https://sites.google.com/site/kansailabor/conference/26th?authuser=0)

\ 

### Awards, Grants and Fellowship

- W-SPRING (JST SPRING) Fellowship, April 2024 – March 2027.
  - Stipend of ¥2,400,000 (JPY) per annum.
  - Grant of ¥500,000 (JPY) per annum.


### Academic Experience

- RA; Research Assistant
	1. RA for Michihito Ando（May 2022--Present）
	1. RA for Hideo Owan（Feb 2023--Present）

\ 

- SA; Student Assistant
	1. Research methods of survey（2021, Toshiyuki Himichi）
	1. Intermediate statistics（2021, Yuki Yanai）
	
\	
	
- TA; Teaching Assistant
  1. Population Economics for Undergraduate (Spring semester 2024, Masahiro Yoshida)
  1. Micro Economics 1 (Spring semester 2024, Hideo Owan)
	1. Population Economics for Graduate students (Spring semester 2023, Masahiro Yoshida)
	1. Introduction to Econometrics (Spring semester 2023, Yasushi Kondo )
	1. Introduction to Quantitative politics（Spring semester 2023, Masahiko Asano）
	1. Intermediate Econometrics (Fall semester 2023, Yasushi Kondo )

\ 

### Programming (Skills and Softwares)

\ 

#### Analysis, Estimation and Data cleaning


- R（Tidyverse R）
- Python

\ 

#### Writing

- Markdown
- LaTeX

\ 

#### Code Management

- [GitHub](https://github.com/kanayama8810)

\ 

### Membership

- Japanese Economic Association
- Asian and Australasian Society of Labour Economics

（`r Sys.Date()` update ）
