---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FXEQV713CW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FXEQV713CW');
</script>


### 金山 隼人（Hayato Kanayama）

\ 

#### 所属

- 早稲田大学大学院 経済学研究科 博士後期課程

\ 

労働政策、制度、慣習が労働者にとってより良いものであるかを、複数の政策・制度の交互作用を検討しつつ分析しています。最近は、飲みニケーションが部下のキャリアに与える影響について研究を行っています。
また、最低賃金の既婚女性労働者への影響に関する研究も行っています。



\ 

#### 研究分野

- 労働経済学
- 人事経済学
- 公共経済学

\ 

#### 研究テーマ

- 最低賃金と既婚女性労働者の就業
- 生活保護・雇用保険の利用と新型コロナウィルス蔓延（立教大学 安藤道人 准教授、帝京大学 古市将人 准教授との共著）
- 飲み上司と部下のキャリア（早稲田大学大学院 経済学研究科 博士後期課程 川太悠史、同研究科 [北川梨津](https://www.ritsukitagawa.com/jpn) との共著）

\ 

#### できごと

- [日本経済学会 春季学会で The Value of Drinking Bosses: Evidence from a Large Manufacturing Company を発表しました](https://confit.atlas.jp/guide/event/jea2024s/subject/2A204-07-04/tables?cryptoId=)
- [Contract Theory Workshopで The Value of Drinking Bosses: Evidence from a Large Manufacturing Company を発表しました](https://sites.google.com/view/ctwz/)
- [早稲田オープン・イノベーション・エコシステム挑戦的研究プログラムの審査評価S区分に採択されました](https://www.waseda.jp/wspring/program/detail/)
- [Asian and Australian Society of Labour Economics 2023 Conference で私達の論文を発表しました](https://virtual.oxfordabstracts.com/#/event/public/4290/submission/245)
- [ワーキングペーパーを載せました: Discontinuous or Kinked Response? Dynamics of Unemployment Insurance and Public Assistance under the COVID-19 Crisis (with Michihito Ando and Masato Furuichi)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4617281)
- [26回 労働経済学コンファレンスでポスター発表をしました。](https://sites.google.com/site/kansailabor/conference/26th?authuser=0)
- [2020年度 高知工科大学 廣井勇賞 受賞](https://www.kochi-tech.ac.jp/news/img/874d9183fe1f3661a60067d98f550bdf.pdf) 

#### 連絡先

- Email  : ha13yato `[at]` toki.waseda.jp
- 郵送先 : 〒162-0041 東京都新宿区早稲田鶴巻町513  121号館601B

（`r Sys.Date()` 最終更新 ）

