---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FXEQV713CW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FXEQV713CW');
</script>


### Hayato Kanayama

\ 

#### Graduate school of Economics, Waseda university 

I am a Ph.D student in Graduate school of Economics, Waseda university. 
My research interests lie primarily in the areas of Labor Economics and Personnel Economics. 
My current research investigates the relationship between socializing and promotion on the firm 
and Another research focus is the labor supply heterogeneity of minimum wage effect on the labor markets.

 



\ 

#### Research Interest

- Labor Economics
- Personnel Economics
- Public Economics

\ 

#### Work in progress

- Minimum wage hikes and the heterogeneity of Labor supply
- Dynamics of Unemeployment Insurance and Public Assistance under COVID-19 (with Michihito Ando and Masato Furuichi)
- The Value of Drinking Bosses（with Yuji Kawata and [Ritsu Kitagawa](https://www.ritsukitagawa.com/home)）

\ 

#### News

- [Presentation (May 2024) : Japanese Economic Association 2024 Spring Meeting](https://confit.atlas.jp/guide/event/jea2024s/subject/2A204-07-04/tables?cryptoId=)
- [Presentation (May 2024) : Contract Theory Workshop](https://sites.google.com/view/ctwz/)
- [Uploaded our working Papers: Discontinuous or Kinked Response? Dynamics of Unemployment Insurance and Public Assistance under the COVID-19 Crisis (with Michihito Ando and Masato Furuichi)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4617281)
- [Presentation (Sep 2023) : Labor Economic Conference](https://sites.google.com/site/kansailabor/conference/26th?authuser=0)
- [Awarded (Nov 2020): Hiroi Isami Award](https://www.kochi-tech.ac.jp/news/img/874d9183fe1f3661a60067d98f550bdf.pdf) 


#### Contact Information

- ha13yato `[at]` toki.waseda.jp

（`r Sys.Date()` update ）

